default:
  shortname: whitman-leaves_of_grass
  collection: whitman-leaves_of_grass
  site_url: https://whitmanarchive.org
  tei_html_xsl: scripts/overrides/tei_to_html.xsl

development:
  data_base: https://whitman-dev.unl.edu/media
  es_path: https://whitman-dev.unl.edu/elastic
  es_index: api_v1
  site_url: https://whitman-dev.unl.edu

production:
  site_url: https://whitmanarchive.org
