default:
  shortname: whitman-leaves_of_grass
  collection: whitman-leaves_of_grass
  site_url: https://whitmanarchive.org
  tei_html_xsl: scripts/overrides/tei_to_html.xsl
  media_base: https://whitmanarchive.org/media
  data_base: https://whitmanarchive.org/media
  variables_html:
    image_large: 1200
    image_thumb: 80
  api_version: "2.0"
  es_index: whitman-api_v2
  threads: 1


